export const REQUEST_CREATE_EVENT_PENDING = 'REQUEST_CREATE_EVENT_PENDING'
export const REQUEST_CREATE_EVENT_SUCCESS = 'REQUEST_CREATE_EVENT_SUCCESS'
export const REQUEST_CREATE_EVENT_FAILURE = 'REQUEST_CREATE_EVENT_FAILURE'
export const REQUEST_CREATE_EVENT_RESET = 'REQUEST_CREATE_EVENT_RESET'